trigger:
- main

pool:
  vmImage: 'macOS-12'

variables:
   - group: epaycoDev

stages:
  - stage: Build
    displayName: Build Android Dev
    jobs:
      # Debug buildg
      - job: Build_Android_Dev
        displayName: Build Dev
        steps:

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '11'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
        
          - task: Gradle@2
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'assembleDebug test'
            displayName: Compile to APK

          - task: CopyFiles@2
            inputs:
              contents: '**/*.apk'
              targetFolder: '$(build.artifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
              publishLocation: 'Container'
          
          - script: mv $(Build.ArtifactStagingDirectory)/app/build/outputs/apk/debug/app-debug.apk $(Build.ArtifactStagingDirectory)/app/build/outputs/apk/debug/app-dev-debug.apk

          - script: ls -R '$(Build.ArtifactStagingDirectory)'
            
          - script: curl -u "cicdintegration_Laurg:viqWDxypzrKLGjzhn7xV" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/debug/app-dev-debug.apk"